---
- name: Create temp directory for doing work in
  command: mktemp -d /tmp/prometheus-ocp-XXXXXX
  register: mktemp
  changed_when: False
  check_mode: no

- name: ensure python dependencies
  pip:
    name:
      - openshift
      - passlib
      - jmespath

- name: Get node-config to check SDN-Plugin type
  k8s_facts:
    verify_ssl: false
    api_version: v1
    kind: ConfigMap
    namespace: openshift-node
    name: node-config-master
  register: node_configmap

- name: Extract networkPluginName from node-config.yml
  set_fact:
    sdn_plugin_name: "{{ node_configmap.resources[0].data['node-config.yaml'] | from_yaml | json_query('networkConfig.networkPluginName') }}"

- name: Check if cluster_prometheus is deployed
  k8s_facts:
    verify_ssl: "{{ k8s_auth_verify_ssl }}"
    api_version: v1
    kind: Deployment
    namespace: '{{ cluster_prometheus_namespace }}'
    label_selectors:
      - k8s-app = {{ cluster_prometheus_namespace }}-operator
  register: prometheus_operator

- name: Search for monitoring wanted labels
  k8s_facts:
    verify_ssl: "{{ k8s_auth_verify_ssl }}"
    api_version: v1
    kind: namespace
    label_selectors:
      -  "{{ cluster_prometheus_namespace_label }}" # search for namespaces with the specified label to deploy prometheus and grafana in there.
  register: namespaces_prom

- name: Search for pushgateway labels
  k8s_facts:
    verify_ssl: "{{ k8s_auth_verify_ssl }}"
    api_version: v1
    kind: namespace
    label_selectors:
      - "{{ cluster_prometheus_namespace_label }}" # search for namespaces with the specified label to deploy prometheus and grafana in there.
      - "pushgateway=true"
  register: namespaces_pushgateway

- name: Check if Thanos is already deployed
  k8s_facts:
    verify_ssl: "{{ k8s_auth_verify_ssl }}"
    api_version: "v1"
    kind: Deployment
    name: thanos-query
    namespace: '{{ cluster_prometheus_namespace }}'
  register: thanos_deployment

- name: Debugging vars
  block:

    - debug:
        msg: "{{ prometheus_operator }}"

  when: playbook_debug