---
- name: Check if grafana is already deployed
  k8s_facts:
    verify_ssl: "{{ k8s_auth_verify_ssl }}"
    api_version: v1
    kind: Deployment
    namespace: '{{ current_namespace.metadata.name }}'
    label_selectors:
      - app=grafana
  register: grafana_deployment

- name: Deploying Grafana in namespace
  block:

  when: grafana_deployment.resources[0] is not defined

- debug:
    msg: "Grafana is already deployed in Project '{{ current_namespace.metadata.name }}'"
  when: grafana_deployment.resources[0] is defined