apiVersion: test.monitoring.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    prometheus: monitoring
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
